Removes jurplel/install-qt-action (#424)

diff --git a/.github/workflows/ci-linux.yml b/.github/workflows/ci-linux.yml
--- a/.github/workflows/ci-linux.yml
+++ b/.github/workflows/ci-linux.yml
@@ -5,57 +5,72 @@ jobs:
   build:
     name: Linux
     runs-on: ubuntu-22.04
-    env:
-      CMAKE_BUILD_PARALLEL_LEVEL: '2'
     steps:
     - name: Checkout source
       uses: actions/checkout@v4
+    - name: Install System Packages
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y flatpak flatpak-builder
+    - name: Add Flathub
+      run: flatpak remote-add --user flathub https://flathub.org/repo/flathub.flatpakrepo
     - name: Generate cache keys
       run: |
-        echo "cargo=${{ runner.os }}-cargo" >> $GITHUB_OUTPUT
-        echo "qt=${{ runner.os }}-qt" >> $GITHUB_OUTPUT
-        echo "build=${{ runner.os }}-build-files-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake', 'CMakePresets.json') }}" >> $GITHUB_OUTPUT
+        echo "flatpak-runtime=${{ runner.os }}-flatpak-runtime-${{ hashFiles('flatpak.yml') }}" >> $GITHUB_OUTPUT
+        echo "flatpak-build=${{ runner.os }}-flatpak-build-${{ hashFiles('flatpak.yml') }}" >> $GITHUB_OUTPUT
       id: cache-keys
-    - name: Restore Cargo home
+    - name: Restore Flatpak runtimes
       uses: actions/cache/restore@v3
       with:
-        path: ~/.cargo
-        key: ${{ steps.cache-keys.outputs.cargo }}
-    - name: Install Qt
-      uses: jurplel/install-qt-action@v4
-      with:
-        version: 6.*
-        aqtversion: '==3.1.*'
-        cache: true
-        cache-key-prefix: ${{ steps.cache-keys.outputs.qt }}
+        path: ~/.local/share/flatpak/runtime
+        key: ${{ steps.cache-keys.outputs.flatpak-runtime }}
+      id: flatpak-runtime
+    - name: Install Flatpak runtimes
+      run: |
+        flatpak install --noninteractive flathub \
+          org.kde.Platform//6.6 org.kde.Sdk//6.6 \
+          org.freedesktop.Sdk.Extension.rust-stable//23.08 \
+          org.freedesktop.Sdk.Extension.llvm17//23.08
+      if: ${{ steps.flatpak-runtime.outputs.cache-hit != 'true' }}
     - name: Restore build files
       uses: actions/cache/restore@v3
       with:
-        path: |
-          build
-          src/target
-        key: ${{ steps.cache-keys.outputs.build }}
-    - name: Run CMake
-      run: cmake --preset linux-release .
-    - name: Build
-      run: cmake --build --preset linux-release
-    - name: Run tests
-      run: cargo test --workspace --exclude core
-      working-directory: src
-    - name: Run Clippy
-      run: cargo clippy --release
-      working-directory: src
+        path: .flatpak-builder
+        key: ${{ steps.cache-keys.outputs.flatpak-build }}
+    - name: Generate Flatpak branch
+      run: |
+        my $name;
+
+        if ($ENV{GITHUB_REF} =~ /^refs\/pull\/(\d+)\//) {
+          $name = "pr-$1";
+        } else {
+          $name = 'dev';
+        }
+
+        open(my $fh, '>>', $ENV{GITHUB_OUTPUT}) || die "Cannot open $ENV{GITHUB_OUTPUT}: $!\n";
+        print $fh "flatpak-branch=$name\n";
+      shell: perl {0}
+      id: flatpak-branch
+    - name: Build Flatpak
+      run: flatpak-builder --default-branch ${{ steps.flatpak-branch.outputs.flatpak-branch }} build flatpak.yml
+    - name: Export Flatpak
+      run: flatpak build-export flatpak build
+    - name: Bundle Flatpak
+      run: flatpak build-bundle flatpak obliteration.flatpak io.github.obhq.Obliteration --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
     - name: Cache build files
       uses: actions/cache/save@v3
       with:
-        path: |
-          build
-          src/target
-        key: ${{ steps.cache-keys.outputs.build }}-${{ github.run_id }}
+        path: .flatpak-builder
+        key: ${{ steps.cache-keys.outputs.flatpak-build }}-${{ github.run_id }}
       if: startsWith(github.ref, 'refs/heads/')
-    - name: Cache Cargo home
+    - name: Cache Flatpak runtimes
       uses: actions/cache/save@v3
       with:
-        path: ~/.cargo
-        key: ${{ steps.cache-keys.outputs.cargo }}-${{ github.run_id }}
+        path: ~/.local/share/flatpak/runtime
+        key: ${{ steps.cache-keys.outputs.flatpak-runtime }}-${{ github.run_id }}
       if: startsWith(github.ref, 'refs/heads/')
+    - name: Upload Flatpak
+      uses: actions/upload-artifact@v3
+      with:
+        name: obliteration-linux-amd64
+        path: obliteration.flatpak
